version: '2.2'
services:
  mysql:
    image: mariadb:10
    container_name: awp_demo_mysql_1
    ports:
      - "8081:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: mysqladmin -uroot ping
      interval: 2s
      timeout: 5s
      retries: 30
  site:
    build: ./
    container_name: awp_demo_wordpress_1
    ports:
      - "2222:22"
      - "80:80"
      - "443:443"
      - "3000:3000"
      - "3001:3001"
    links:
      - mysql
    depends_on:
      mysql:
        condition: service_healthy
